"""
Demo Mode — Pre-stored dummy results for testing without consuming LLM tokens.
Toggle "Demo Mode" in the sidebar to use these instead of real API calls.
"""

DEMO_SUMMARY = """## Executive Summary

This is a Phase III, randomized, double-blind, placebo-controlled, multicenter clinical trial evaluating the efficacy and safety of Metformin Extended Release (XR) 1000mg in adult patients with Type 2 Diabetes Mellitus (T2DM) inadequately controlled on diet and exercise alone.

**Key Points:**
- **Study Duration:** 24 weeks with a 4-week screening and 2-week washout period
- **Population:** 500 adult patients (18-75 years) with HbA1c 7.0-10.0%
- **Primary Objective:** Demonstrate superior glycemic control (HbA1c reduction) vs. placebo at Week 24
- **Design:** 1:1 randomization with stratification by baseline HbA1c and BMI
- **Safety Monitoring:** Independent Data Safety Monitoring Board (DSMB) with planned interim analysis at Week 12

The trial follows ICH M11 protocol template structure and ICH-GCP E6(R2) guidelines, with comprehensive safety monitoring for lactic acidosis, hepatic events, and cardiovascular outcomes.
"""

DEMO_ENTITIES = {
    "study_phase": "Phase III",
    "study_design": "Randomized, double-blind, placebo-controlled, multicenter",
    "sample_size": "500 patients (250 per arm)",
    "drugs": [
        {"name": "Metformin XR", "dosage": "1000mg once daily", "route": "Oral"},
        {"name": "Placebo", "dosage": "Matching tablet once daily", "route": "Oral"},
    ],
    "primary_endpoints": [
        "Change from baseline in HbA1c at Week 24",
        "Proportion of patients achieving HbA1c < 7.0% at Week 24",
    ],
    "secondary_endpoints": [
        "Change in fasting plasma glucose (FPG) at Week 24",
        "Change in body weight from baseline",
        "Time to rescue medication",
    ],
    "adverse_events": [
        {"event": "Lactic acidosis", "severity": "HIGH", "monitoring": "Serial lactate levels"},
        {"event": "Gastrointestinal disorders", "severity": "MEDIUM", "monitoring": "Patient diary"},
        {"event": "Vitamin B12 deficiency", "severity": "LOW", "monitoring": "Annual serum B12"},
        {"event": "Hypoglycemia", "severity": "MEDIUM", "monitoring": "SMBG + event log"},
    ],
    "inclusion_criteria": [
        "Adults 18-75 years",
        "Diagnosed T2DM (ADA criteria)",
        "HbA1c 7.0-10.0%",
        "BMI 25-40 kg/m2",
        "Stable diet/exercise regimen >= 8 weeks",
    ],
    "exclusion_criteria": [
        "Type 1 diabetes",
        "eGFR < 45 mL/min/1.73m2",
        "History of lactic acidosis",
        "Active liver disease (ALT > 3x ULN)",
        "Pregnancy or lactation",
    ],
    "sponsor": "PharmaCorp International",
    "protocol_number": "PC-DM-2024-003",
}

DEMO_RISK = {
    "findings": [
        {
            "title": "Missing Rescue Medication Criteria",
            "severity": "HIGH",
            "category": "rescue_criteria",
            "description": "The protocol does not clearly define the HbA1c threshold or timepoint at which rescue medication should be initiated for patients with inadequate glycemic control.",
            "section_reference": "Section 6.2 — Concomitant Therapy",
            "evidence": "No explicit rescue criteria found in the protocol text. Section mentions 'rescue therapy may be considered' without defined thresholds.",
            "recommendation": "Define explicit rescue criteria (e.g., HbA1c > 11% at any visit, or confirmed FPG > 270 mg/dL on 2 consecutive visits).",
            "agent": "safety",
            "agent_label": "Safety Agent",
            "agent_icon": "shield",
            "agent_color": "red",
            "source_chunk": "Section 6 — Study Treatment",
            "agents_agree": ["safety", "regulatory"],
            "agreement_count": 2,
            "verified": "verified",
            "verification_score": 0.72,
            "verification_note": "Evidence verified against source document",
            "fix_suggestion": {
                "text": "Add explicit rescue criteria to Section 6.2 — Concomitant Therapy:\n• HbA1c > 11% confirmed at any scheduled visit → initiate rescue therapy\n• FPG > 270 mg/dL on 2 consecutive visits (≥ 1 week apart) → initiate rescue therapy\n• Document the rescue medication options, dose ranges, and statistical handling of post-rescue data.",
                "type": "protocol_text",
                "confidence": "high",
            },
        },
        {
            "title": "DSMB Charter Not Referenced",
            "severity": "HIGH",
            "category": "dsmb_oversight",
            "description": "While an interim analysis is mentioned at Week 12, the DSMB charter and stopping rules are not provided or referenced in the protocol.",
            "section_reference": "Section 9 — Oversight & Governance",
            "evidence": "Protocol states 'An independent DSMB will review safety data' but no charter or stopping rules are referenced.",
            "recommendation": "Include reference to DSMB charter document with pre-specified stopping boundaries (O'Brien-Fleming or similar).",
            "agent": "safety",
            "agent_label": "Safety Agent",
            "agent_icon": "shield",
            "agent_color": "red",
            "source_chunk": "Section 9 — Governance",
            "agents_agree": ["safety", "statistics"],
            "agreement_count": 2,
            "verified": "verified",
            "verification_score": 0.85,
            "verification_note": "Evidence verified against source document",
            "fix_suggestion": {
                "text": "Add a DSMB Charter reference in Section 9 — Oversight & Governance:\n• Reference DSMB Charter document number and version\n• Include pre-specified stopping boundaries (O'Brien-Fleming alpha-spending)\n• Define unblinding rules and quorum requirements.",
                "type": "protocol_text",
                "confidence": "high",
            },
        },
        {
            "title": "Sample Size Justification Incomplete",
            "severity": "HIGH",
            "category": "sample_size",
            "description": "The power calculation assumes an HbA1c difference of 0.5% but does not specify the assumed standard deviation or dropout rate used to arrive at N=500.",
            "section_reference": "Section 10 — Statistical Considerations",
            "evidence": "States '500 patients provides 90% power' but SD and dropout assumptions are missing.",
            "recommendation": "Specify assumed SD (typically 1.0-1.2% for HbA1c), expected dropout rate (15-20%), and alpha level (0.05 two-sided).",
            "agent": "statistics",
            "agent_label": "Statistics Agent",
            "agent_icon": "chart",
            "agent_color": "blue",
            "source_chunk": "Section 10 — Statistics",
            "agents_agree": ["statistics"],
            "agreement_count": 1,
            "verified": "verified",
            "verification_score": 0.78,
            "verification_note": "Evidence verified against source document",
            "fix_suggestion": {
                "text": "Complete the sample size justification in Section 10 — Statistical Considerations:\n• State assumed SD (e.g., 1.1% for HbA1c change)\n• State expected dropout rate (e.g., 15%)\n• Confirm alpha = 0.05 two-sided, power = 90%\n• Show: N = 2 × [(Zα/2 + Zβ)² × 2σ²] / δ² + dropout adjustment",
                "type": "statistical",
                "confidence": "high",
            },
        },
        {
            "title": "No Multiplicity Adjustment for Secondary Endpoints",
            "severity": "MEDIUM",
            "category": "multiplicity",
            "description": "Three secondary endpoints are listed but no multiplicity adjustment strategy (e.g., Hochberg, Holm, gatekeeping) is specified.",
            "section_reference": "Section 10.3 — Secondary Analyses",
            "evidence": "Secondary endpoints listed without any mention of alpha control or testing hierarchy.",
            "recommendation": "Implement a gatekeeping strategy: test secondary endpoints only if primary is significant, with Hochberg adjustment among secondaries.",
            "agent": "statistics",
            "agent_label": "Statistics Agent",
            "agent_icon": "chart",
            "agent_color": "blue",
            "source_chunk": "Section 10 — Statistics",
            "agents_agree": ["statistics"],
            "agreement_count": 1,
            "verified": "partial",
            "verification_score": 0.45,
            "verification_note": "Partial match — some supporting text found",
            "fix_suggestion": {
                "text": "Add multiplicity control to Section 10.3 — Secondary Analyses:\n• Implement gatekeeping strategy: test secondary endpoints only if primary is statistically significant (p < 0.05)\n• Among secondary endpoints, apply Hochberg step-up procedure\n• Pre-specify the testing hierarchy in the SAP.",
                "type": "statistical",
                "confidence": "high",
            },
        },
        {
            "title": "Missing Data Handling Not Specified",
            "severity": "MEDIUM",
            "category": "missing_data",
            "description": "No strategy for handling missing data is described. For a 24-week trial with expected dropouts, this is a critical gap.",
            "section_reference": "Section 10 — Statistical Considerations",
            "evidence": "Statistical section does not mention LOCF, MMRM, multiple imputation, or any missing data approach.",
            "recommendation": "Specify MMRM as primary analysis and pattern-mixture models or tipping-point analysis as sensitivity analyses per ICH E9(R1).",
            "agent": "statistics",
            "agent_label": "Statistics Agent",
            "agent_icon": "chart",
            "agent_color": "blue",
            "source_chunk": "Section 10 — Statistics",
            "agents_agree": ["statistics", "regulatory"],
            "agreement_count": 2,
            "verified": "verified",
            "verification_score": 0.68,
            "verification_note": "Evidence verified against source document",
            "fix_suggestion": {
                "text": "Specify missing data strategy in Section 10 — Statistical Considerations:\n• Primary analysis: Mixed Model Repeated Measures (MMRM)\n• Sensitivity: Multiple Imputation under Missing-at-Random\n• Stress test: Tipping-point analysis per ICH E9(R1) estimand framework\n• Define intercurrent events and their handling strategies.",
                "type": "statistical",
                "confidence": "high",
            },
        },
        {
            "title": "Concomitant Medication Washout Unclear",
            "severity": "MEDIUM",
            "category": "safety_monitoring",
            "description": "The 2-week washout period may be insufficient for patients previously on sulfonylureas (half-life considerations) or TZDs (prolonged pharmacodynamic effects).",
            "section_reference": "Section 5.2 — Washout Period",
            "evidence": "Protocol specifies a 'minimum 2-week washout for all prior anti-diabetic medications' without drug-class differentiation.",
            "recommendation": "Specify washout periods by drug class: SU >= 4 weeks, TZD >= 8 weeks, DPP4i >= 2 weeks.",
            "agent": "safety",
            "agent_label": "Safety Agent",
            "agent_icon": "shield",
            "agent_color": "red",
            "source_chunk": "Section 5 — Study Design",
            "agents_agree": ["safety"],
            "agreement_count": 1,
            "verified": "verified",
            "verification_score": 0.81,
            "verification_note": "Evidence verified against source document",
            "fix_suggestion": {
                "text": "Clarify washout periods in Section 5.2 — Washout Period by drug class:\n• Sulfonylureas: ≥ 4 weeks (long-acting metabolites)\n• Thiazolidinediones: ≥ 8 weeks (prolonged PD effects)\n• DPP-4 inhibitors: ≥ 2 weeks\n• SGLT2 inhibitors: ≥ 2 weeks\n• GLP-1 agonists: ≥ 5 half-lives of the specific agent.",
                "type": "protocol_text",
                "confidence": "high",
            },
        },
        {
            "title": "Investigator Qualifications Missing (ICH M11 Section 14)",
            "severity": "MEDIUM",
            "category": "ich_gcp_structure",
            "description": "No section describes required investigator qualifications, training requirements, or delegation of responsibilities.",
            "section_reference": "ICH M11 Section 14 — Ethics & Regulatory",
            "evidence": "Protocol does not contain investigator qualification requirements or CV/training provisions.",
            "recommendation": "Add section per ICH M11 Section 14 and ICH-GCP 4.1: investigator qualifications, GCP training, delegation log requirements.",
            "agent": "regulatory",
            "agent_label": "Regulatory Agent",
            "agent_icon": "clipboard",
            "agent_color": "green",
            "source_chunk": "Overall Document Structure",
            "agents_agree": ["regulatory"],
            "agreement_count": 1,
            "verified": "partial",
            "verification_score": 0.42,
            "verification_note": "Partial match — some supporting text found",
            "fix_suggestion": {
                "text": "Add Investigator Qualifications section per ICH M11 Section 14 and ICH-GCP 4.1:\n• Require current CV of PI and sub-investigators\n• Document GCP training certificates (within 3 years)\n• Include delegation of authority log template\n• Reference 21 CFR Part 312.53 for US sites.",
                "type": "regulatory",
                "confidence": "high",
            },
        },
        {
            "title": "Protocol Deviation Handling Not Defined",
            "severity": "MEDIUM",
            "category": "deviation_handling",
            "description": "No procedure for identifying, documenting, and reporting protocol deviations is described.",
            "section_reference": "ICH M11 Section 13 — Oversight",
            "evidence": "No mention of protocol deviation classification, reporting timelines, or corrective actions.",
            "recommendation": "Define protocol deviation categories (major/minor), reporting timelines, and CAPA process per ICH M11 Section 13.",
            "agent": "regulatory",
            "agent_label": "Regulatory Agent",
            "agent_icon": "clipboard",
            "agent_color": "green",
            "source_chunk": "Overall Document Structure",
            "agents_agree": ["regulatory"],
            "agreement_count": 1,
            "verified": "unverified",
            "verification_score": 0.18,
            "verification_note": "Evidence not found in source document — may be hallucinated",
            "fix_suggestion": {
                "text": "Add Protocol Deviation Procedures per ICH M11 Section 13:\n• Define categories: Major (affects safety/data integrity) vs. Minor\n• Reporting timelines: Major → Sponsor within 24h, IRB within 5 business days\n• Require CAPA documentation for all major deviations\n• Track in deviation log with root cause analysis.",
                "type": "regulatory",
                "confidence": "high",
            },
        },
        {
            "title": "Missing Patient Reported Outcomes",
            "severity": "LOW",
            "category": "endpoint_definition",
            "description": "No validated quality of life instrument (e.g., DTSQ, EQ-5D) is included despite regulatory expectation for patient-centric outcomes.",
            "section_reference": "Section 7 — Assessments",
            "evidence": "Assessment schedule does not include any patient-reported outcome measures.",
            "recommendation": "Consider adding DTSQ (Diabetes Treatment Satisfaction Questionnaire) as an exploratory endpoint.",
            "agent": "statistics",
            "agent_label": "Statistics Agent",
            "agent_icon": "chart",
            "agent_color": "blue",
            "source_chunk": "Section 7 — Assessments",
            "agents_agree": ["statistics", "regulatory"],
            "agreement_count": 2,
            "verified": "verified",
            "verification_score": 0.65,
            "verification_note": "Evidence verified against source document",
            "fix_suggestion": {
                "text": "Add Patient-Reported Outcomes to Section 7 — Assessments:\n• Include DTSQ (Diabetes Treatment Satisfaction Questionnaire) as exploratory endpoint\n• Consider EQ-5D-5L for health-related quality of life\n• Administer at Baseline, Week 12, and Week 24\n• Pre-specify MID (Minimally Important Difference) thresholds.",
                "type": "protocol_text",
                "confidence": "high",
            },
        },
        {
            "title": "Record Retention Period Not Specified",
            "severity": "LOW",
            "category": "data_integrity",
            "description": "The protocol does not specify the required duration for maintaining essential documents and source records.",
            "section_reference": "ICH M11 Section 15 — Data Management & Records",
            "evidence": "No mention of document archival requirements or minimum retention timelines.",
            "recommendation": "Specify minimum 15-year retention or per local regulations, whichever is longer (ICH M11 Section 15).",
            "agent": "regulatory",
            "agent_label": "Regulatory Agent",
            "agent_icon": "clipboard",
            "agent_color": "green",
            "source_chunk": "Overall Document Structure",
            "agents_agree": ["regulatory"],
            "agreement_count": 1,
            "verified": "partial",
            "verification_score": 0.38,
            "verification_note": "Partial match — some supporting text found",
            "fix_suggestion": {
                "text": "Add Record Retention requirements per ICH M11 Section 15:\n• Minimum 15 years from study completion, or per local regulations, whichever is longer\n• Specify storage conditions (secure, access-controlled, climate-controlled)\n• Define electronic record backup and migration procedures\n• Identify responsible party for long-term archival.",
                "type": "regulatory",
                "confidence": "high",
            },
        },
    ],
    "verification": {
        "verified": 6,
        "partial": 3,
        "unverified": 1,
        "total": 10,
        "trust_score": 75,
    },
    "agent_results": {
        "safety": {
            "label": "Safety Agent",
            "role": "Pharmacovigilance Reviewer",
            "confidence": 0.88,
            "finding_count": 4,
        },
        "statistics": {
            "label": "Statistics Agent",
            "role": "Biostatistician",
            "confidence": 0.91,
            "finding_count": 4,
        },
        "regulatory": {
            "label": "Regulatory Agent",
            "role": "Regulatory Affairs Specialist",
            "confidence": 0.85,
            "finding_count": 4,
        },
    },
    "total_findings": 10,
    "high_count": 3,
    "medium_count": 5,
    "low_count": 2,
}

DEMO_CONSENT = {
    "completeness_score": 83,
    "present_count": 10,
    "total_required": 12,
    "consent_elements": {
        "study_purpose": True,
        "procedures_described": True,
        "duration_stated": True,
        "risks_disclosed": True,
        "benefits_described": True,
        "alternatives_mentioned": True,
        "confidentiality_addressed": True,
        "voluntary_participation": True,
        "withdrawal_rights": True,
        "compensation_mentioned": False,
        "contact_information": True,
        "irb_information": False,
    },
    "findings": [
        {
            "title": "Missing Compensation Information",
            "severity": "MEDIUM",
            "category": "Consent Compliance",
            "description": "ICH-GCP 4.8.10(j) requires disclosure of compensation and treatment available for trial-related injury. This was not found in the consent form.",
            "recommendation": "Add a section describing compensation for participation and treatment for trial-related injuries.",
        },
        {
            "title": "IRB/IEC Contact Missing",
            "severity": "LOW",
            "category": "Consent Compliance",
            "description": "The consent form should include contact information for the IRB/IEC for questions about patient rights.",
            "recommendation": "Add IRB contact details including phone number and address.",
        },
    ],
}

DEMO_TOKEN_USAGE = {
    "total_tokens": 4826,
    "total_prompt_tokens": 3512,
    "total_completion_tokens": 1314,
    "calls": 3,
    "cache_hits": 0,
}

DEMO_COMPARISON = {
    "document_count": 2,
    "documents": [
        {
            "filename": "Protocol_v1.0_Draft.pdf",
            "doc_type": "Clinical Trial Protocol",
            "analyzed_at": "2025-01-15T09:30:00",
            "quality_score": 58,
            "quality_grade": "C",
            "finding_counts": {"total": 14, "high": 5, "medium": 7, "low": 2},
            "trust_score": 68,
            "compliance_pct": 64,
        },
        {
            "filename": "Protocol_v2.0_Revised.pdf",
            "doc_type": "Clinical Trial Protocol",
            "analyzed_at": "2025-01-22T14:15:00",
            "quality_score": 76,
            "quality_grade": "B",
            "finding_counts": {"total": 10, "high": 3, "medium": 5, "low": 2},
            "trust_score": 75,
            "compliance_pct": 82,
        },
    ],
    "shared_findings": [
        {
            "title": "Missing Rescue Medication Criteria",
            "severity": "HIGH",
            "category": "rescue_criteria",
            "found_in": ["Protocol_v1.0_Draft.pdf", "Protocol_v2.0_Revised.pdf"],
            "count": 2,
        },
        {
            "title": "No Multiplicity Adjustment for Secondary Endpoints",
            "severity": "MEDIUM",
            "category": "multiplicity",
            "found_in": ["Protocol_v1.0_Draft.pdf", "Protocol_v2.0_Revised.pdf"],
            "count": 2,
        },
        {
            "title": "Missing Data Handling Not Specified",
            "severity": "MEDIUM",
            "category": "missing_data",
            "found_in": ["Protocol_v1.0_Draft.pdf", "Protocol_v2.0_Revised.pdf"],
            "count": 2,
        },
    ],
    "unique_findings": {
        "Protocol_v1.0_Draft.pdf": [
            "Randomization Procedure Not Described",
            "No Site Monitoring Plan",
            "Blinding Procedure Incomplete",
            "No SAE Reporting Timeline",
        ],
        "Protocol_v2.0_Revised.pdf": [
            "Record Retention Period Not Specified",
        ],
    },
    "trend": {
        "quality_delta": 18,
        "quality_direction": "improved",
        "findings_delta": -4,
        "findings_direction": "fewer",
        "previous_doc": "Protocol_v1.0_Draft.pdf",
        "current_doc": "Protocol_v2.0_Revised.pdf",
    },
}

# ═══════════════════════════════════════════════════════════════════════════
# Multi-Document Cross-Comparison Demo Data
# Simulates: Protocol vs CSR vs Consent Form for the same study
# ═══════════════════════════════════════════════════════════════════════════

DEMO_CROSS_DOC_COMPARISON = {
    "document_count": 3,
    "documents": [
        {
            "filename": "Protocol_PC-DM-2024-003.pdf",
            "doc_type": "Clinical Protocol",
            "quality_score": 72,
            "quality_grade": "B",
            "finding_counts": {"total": 10, "high": 3, "medium": 5, "low": 2},
            "extracted_fields": {
                "age_criteria": "18-75 years",
                "dosage": "Metformin XR 1000 mg once daily",
                "inclusion_criteria": [
                    "Adults 18-75 years",
                    "Diagnosed T2DM (ADA criteria)",
                    "HbA1c 7.0-10.0%",
                    "BMI 25-40 kg/m2",
                    "Stable diet/exercise regimen >= 8 weeks",
                ],
                "exclusion_criteria": [
                    "Type 1 diabetes",
                    "eGFR < 45 mL/min/1.73m2",
                    "History of lactic acidosis",
                    "Active liver disease (ALT > 3x ULN)",
                    "Pregnancy or lactation",
                ],
                "primary_endpoints": [
                    "Change from baseline in HbA1c at Week 24",
                    "Proportion of patients achieving HbA1c < 7.0% at Week 24",
                ],
                "secondary_endpoints": [
                    "Change in fasting plasma glucose (FPG) at Week 24",
                    "Change in body weight from baseline",
                    "Time to rescue medication",
                ],
                "safety_risks": [
                    "Lactic acidosis",
                    "Gastrointestinal disorders",
                    "Vitamin B12 deficiency",
                    "Hypoglycemia",
                ],
                "sample_size": "500 patients (250 per arm)",
                "study_phase": "Phase III",
                "study_duration": "24 weeks",
                "drug_name": "Metformin XR",
            },
            "summary": "Phase III RCT of Metformin XR 1000 mg vs placebo in 500 T2DM patients over 24 weeks, measuring HbA1c reduction as primary endpoint.",
        },
        {
            "filename": "CSR_PC-DM-2024-003_Final.pdf",
            "doc_type": "Clinical Study Report",
            "quality_score": 68,
            "quality_grade": "C",
            "finding_counts": {"total": 8, "high": 2, "medium": 4, "low": 2},
            "extracted_fields": {
                "age_criteria": "18-75 years",
                "dosage": "Metformin XR 1000 mg once daily",
                "inclusion_criteria": [
                    "Adults aged 18 to 75",
                    "Type 2 diabetes diagnosed per ADA guidelines",
                    "HbA1c between 7.0% and 10.0%",
                    "BMI 25-40 kg/m2",
                ],
                "exclusion_criteria": [
                    "Type 1 diabetes",
                    "eGFR below 45 mL/min/1.73m2",
                    "History of lactic acidosis",
                    "Significant hepatic impairment",
                ],
                "primary_endpoints": [
                    "Change from baseline in HbA1c at Week 24",
                ],
                "secondary_endpoints": [
                    "Change in fasting plasma glucose at Week 24",
                    "Body weight change from baseline",
                ],
                "safety_risks": [
                    "Lactic acidosis",
                    "GI adverse events (nausea, diarrhea)",
                    "Vitamin B12 deficiency",
                ],
                "sample_size": "487 patients randomized (243 active, 244 placebo)",
                "study_phase": "Phase III",
                "study_duration": "24 weeks",
                "drug_name": "Metformin XR",
            },
            "summary": "Phase III CSR for Metformin XR showing statistically significant HbA1c reduction vs placebo. 487 patients completed 24-week treatment.",
        },
        {
            "filename": "Consent_Form_PC-DM-2024-003.pdf",
            "doc_type": "Consent Form",
            "quality_score": 65,
            "quality_grade": "C",
            "finding_counts": {"total": 5, "high": 1, "medium": 3, "low": 1},
            "extracted_fields": {
                "age_criteria": "18-75 years old",
                "dosage": "Metformin XR 1000 mg tablet taken once per day",
                "inclusion_criteria": None,
                "exclusion_criteria": None,
                "primary_endpoints": None,
                "secondary_endpoints": None,
                "safety_risks": [
                    "Lactic acidosis (rare but serious)",
                    "Stomach upset, nausea, diarrhea",
                    "Low vitamin B12 levels",
                ],
                "sample_size": "About 500 participants",
                "study_phase": "Phase III",
                "study_duration": "About 6 months",
                "drug_name": "Metformin XR",
            },
            "summary": "Informed consent for a Phase III study of Metformin XR 1000 mg for Type 2 Diabetes. Describes risks, duration, and patient rights.",
        },
    ],
    "pairwise_comparisons": [
        {
            "doc_a": "Protocol_PC-DM-2024-003.pdf",
            "doc_a_type": "Clinical Protocol",
            "doc_b": "CSR_PC-DM-2024-003_Final.pdf",
            "doc_b_type": "Clinical Study Report",
            "field_comparisons": [
                {"field": "Age Criteria", "status": "match", "detail": "Consistent across documents", "severity": "LOW", "doc_a_value": "18-75 years", "doc_b_value": "18-75 years"},
                {"field": "Drug Dosage", "status": "match", "detail": "Consistent across documents", "severity": "LOW", "doc_a_value": "Metformin XR 1000 mg once daily", "doc_b_value": "Metformin XR 1000 mg once daily"},
                {"field": "Inclusion Criteria", "status": "minor_diff", "detail": "Same criteria, minor wording differences (e.g. 'Adults 18-75 years' vs 'Adults aged 18 to 75'). CSR missing the diet/exercise stability requirement.", "severity": "LOW", "doc_a_value": "Adults 18-75 years; Diagnosed T2DM (ADA criteria); HbA1c 7.0-10.0%; BMI 25-40 kg/m2; Stable diet/exercise regimen >= 8 weeks", "doc_b_value": "Adults aged 18 to 75; Type 2 diabetes diagnosed per ADA guidelines; HbA1c between 7.0% and 10.0%; BMI 25-40 kg/m2"},
                {"field": "Exclusion Criteria", "status": "minor_diff", "detail": "Pregnancy/lactation exclusion present in Protocol but absent in CSR listing", "severity": "MEDIUM", "doc_a_value": "Type 1 diabetes; eGFR < 45; History of lactic acidosis; Active liver disease (ALT > 3x ULN); Pregnancy or lactation", "doc_b_value": "Type 1 diabetes; eGFR below 45; History of lactic acidosis; Significant hepatic impairment"},
                {"field": "Primary Endpoints", "status": "mismatch", "detail": "Protocol lists 2 co-primary endpoints; CSR lists only 1. Missing: proportion achieving HbA1c < 7.0%", "severity": "HIGH", "doc_a_value": "Change from baseline in HbA1c at Week 24; Proportion achieving HbA1c < 7.0% at Week 24", "doc_b_value": "Change from baseline in HbA1c at Week 24"},
                {"field": "Secondary Endpoints", "status": "missing", "detail": "'Time to rescue medication' absent from CSR", "severity": "MEDIUM", "doc_a_value": "FPG change; Body weight change; Time to rescue medication", "doc_b_value": "FPG change; Body weight change"},
                {"field": "Safety Risks", "status": "minor_diff", "detail": "CSR does not list Hypoglycemia as a safety risk, but Protocol does", "severity": "MEDIUM", "doc_a_value": "Lactic acidosis; GI disorders; Vitamin B12 deficiency; Hypoglycemia", "doc_b_value": "Lactic acidosis; GI adverse events; Vitamin B12 deficiency"},
                {"field": "Sample Size", "status": "minor_diff", "detail": "Protocol planned 500, CSR reports 487 randomized — this is expected", "severity": "LOW", "doc_a_value": "500 patients (250 per arm)", "doc_b_value": "487 patients randomized (243 active, 244 placebo)"},
                {"field": "Study Phase", "status": "match", "detail": "Consistent across documents", "severity": "LOW", "doc_a_value": "Phase III", "doc_b_value": "Phase III"},
                {"field": "Study Duration", "status": "match", "detail": "Consistent across documents", "severity": "LOW", "doc_a_value": "24 weeks", "doc_b_value": "24 weeks"},
                {"field": "Drug Name", "status": "match", "detail": "Consistent across documents", "severity": "LOW", "doc_a_value": "Metformin XR", "doc_b_value": "Metformin XR"},
            ],
            "issues": [
                {"field": "Inclusion Criteria", "status": "minor_diff", "detail": "CSR missing diet/exercise stability requirement", "severity": "LOW", "doc_a_value": "5 criteria", "doc_b_value": "4 criteria"},
                {"field": "Exclusion Criteria", "status": "minor_diff", "detail": "Pregnancy/lactation exclusion present in Protocol but absent in CSR listing", "severity": "MEDIUM", "doc_a_value": "5 criteria", "doc_b_value": "4 criteria"},
                {"field": "Primary Endpoints", "status": "mismatch", "detail": "Protocol lists 2 co-primary endpoints; CSR lists only 1", "severity": "HIGH", "doc_a_value": "2 endpoints", "doc_b_value": "1 endpoint"},
                {"field": "Secondary Endpoints", "status": "missing", "detail": "'Time to rescue medication' absent from CSR", "severity": "MEDIUM", "doc_a_value": "3 endpoints", "doc_b_value": "2 endpoints"},
                {"field": "Safety Risks", "status": "minor_diff", "detail": "Hypoglycemia not listed in CSR safety risks", "severity": "MEDIUM", "doc_a_value": "4 risks", "doc_b_value": "3 risks"},
            ],
        },
        {
            "doc_a": "Protocol_PC-DM-2024-003.pdf",
            "doc_a_type": "Clinical Protocol",
            "doc_b": "Consent_Form_PC-DM-2024-003.pdf",
            "doc_b_type": "Consent Form",
            "field_comparisons": [
                {"field": "Age Criteria", "status": "match", "detail": "Consistent across documents", "severity": "LOW", "doc_a_value": "18-75 years", "doc_b_value": "18-75 years old"},
                {"field": "Drug Dosage", "status": "minor_diff", "detail": "Same dose, lay language in consent (tablet taken once per day vs once daily)", "severity": "LOW", "doc_a_value": "Metformin XR 1000 mg once daily", "doc_b_value": "Metformin XR 1000 mg tablet taken once per day"},
                {"field": "Inclusion Criteria", "status": "missing", "detail": "Consent Form does not list specific inclusion criteria", "severity": "MEDIUM", "doc_a_value": "5 criteria listed", "doc_b_value": "\u2014"},
                {"field": "Exclusion Criteria", "status": "missing", "detail": "Consent Form does not list specific exclusion criteria", "severity": "MEDIUM", "doc_a_value": "5 criteria listed", "doc_b_value": "\u2014"},
                {"field": "Primary Endpoints", "status": "missing", "detail": "Consent Form does not describe primary endpoints — patients should understand what is being measured", "severity": "HIGH", "doc_a_value": "HbA1c change; Achievement < 7.0%", "doc_b_value": "\u2014"},
                {"field": "Safety Risks", "status": "minor_diff", "detail": "Consent uses lay language. Hypoglycemia missing from consent but present in Protocol", "severity": "MEDIUM", "doc_a_value": "Lactic acidosis; GI disorders; Vitamin B12 deficiency; Hypoglycemia", "doc_b_value": "Lactic acidosis (rare but serious); Stomach upset, nausea, diarrhea; Low vitamin B12 levels"},
                {"field": "Sample Size", "status": "minor_diff", "detail": "Consent says 'About 500' — appropriate lay simplification", "severity": "LOW", "doc_a_value": "500 patients (250 per arm)", "doc_b_value": "About 500 participants"},
                {"field": "Study Duration", "status": "minor_diff", "detail": "Consent says 'About 6 months' vs Protocol '24 weeks' — equivalent", "severity": "LOW", "doc_a_value": "24 weeks", "doc_b_value": "About 6 months"},
                {"field": "Drug Name", "status": "match", "detail": "Consistent across documents", "severity": "LOW", "doc_a_value": "Metformin XR", "doc_b_value": "Metformin XR"},
            ],
            "issues": [
                {"field": "Inclusion Criteria", "status": "missing", "detail": "Consent Form does not list inclusion criteria", "severity": "MEDIUM", "doc_a_value": "5 criteria", "doc_b_value": "\u2014"},
                {"field": "Exclusion Criteria", "status": "missing", "detail": "Consent Form does not list exclusion criteria", "severity": "MEDIUM", "doc_a_value": "5 criteria", "doc_b_value": "\u2014"},
                {"field": "Primary Endpoints", "status": "missing", "detail": "Consent Form does not describe study endpoints", "severity": "HIGH", "doc_a_value": "2 endpoints", "doc_b_value": "\u2014"},
                {"field": "Safety Risks", "status": "minor_diff", "detail": "Hypoglycemia missing from Consent Form", "severity": "MEDIUM", "doc_a_value": "4 risks", "doc_b_value": "3 risks"},
            ],
        },
        {
            "doc_a": "CSR_PC-DM-2024-003_Final.pdf",
            "doc_a_type": "Clinical Study Report",
            "doc_b": "Consent_Form_PC-DM-2024-003.pdf",
            "doc_b_type": "Consent Form",
            "field_comparisons": [
                {"field": "Age Criteria", "status": "match", "detail": "Consistent across documents", "severity": "LOW", "doc_a_value": "18-75 years", "doc_b_value": "18-75 years old"},
                {"field": "Drug Dosage", "status": "minor_diff", "detail": "Same dose, lay language", "severity": "LOW", "doc_a_value": "Metformin XR 1000 mg once daily", "doc_b_value": "Metformin XR 1000 mg tablet once per day"},
                {"field": "Safety Risks", "status": "match", "detail": "Both list lactic acidosis, GI events, and B12 deficiency", "severity": "LOW", "doc_a_value": "Lactic acidosis; GI adverse events; Vitamin B12 deficiency", "doc_b_value": "Lactic acidosis; Stomach upset; Low vitamin B12 levels"},
                {"field": "Drug Name", "status": "match", "detail": "Consistent across documents", "severity": "LOW", "doc_a_value": "Metformin XR", "doc_b_value": "Metformin XR"},
            ],
            "issues": [],
        },
    ],
    "total_issues": 9,
    "issue_counts": {"HIGH": 2, "MEDIUM": 5, "LOW": 2},
    "risk_score": {
        "score": 59,
        "grade": "C",
        "label": "Notable inconsistencies — review needed",
    },
}
